# -*- coding: utf-8 -*-
"""Consumir modelo via web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvwzZujD3N0uYFDNBO-srLHdzBFa6NG9
"""

import numpy as np
import json
import requests

# Load dataset
dataset = np.load("historial_1D.npy")

# Split into train and validation sets
indexes = np.arange(dataset.shape[0])
np.random.shuffle(indexes)
train_index = indexes[: int(0.8 * dataset.shape[0])]
val_index = indexes[int(0.8 * dataset.shape[0]):]
train_dataset = dataset[train_index]
val_dataset = dataset[val_index]

# Convert the validation dataset to a list
val_dataset_list = val_dataset.tolist()
max_idx = 385 # funciona

# Example index, replace with the actual logic to get the max index

# Create the JSON payload
data = {
    "val_dataset": val_dataset_list,
    "max_idx": max_idx
}

# Convert to JSON string
json_data = json.dumps(data)

# Send the JSON payload to the server
response = requests.post("http://127.0.0.1:5000/predict", headers={"Content-Type": "application/json"}, data=json_data)
print(response.json())